---
- hosts: "{{maquinas}}"
  gather_facts: no

  tasks:
  - name: check reachability | Try connection  on host and port. For now must be used IP not hostname
    check_connection:
      host: "{{host}}"
      port: "{{port}}"
    no_log: false
