---
- hosts: client-01

  tasks:
  - name: find folders.
    find:
      paths: /
      recurse: no
      file_type: directory
    register: output
  - debug: var=item.path
    with_items: "{{ output.files }}"
