---
- name: Get folders
  hosts: client-01
  vars:
    Folders: []
  tasks:
  - name: find folders.
    become: true
    find:
      paths: /
      depth: 3
      recurse: yes
      file_type: directory
      excludes: "proc"
    register: output

  - name: Add files to the list
    no_log: true
    set_fact:
      Folders: "{{ Folders + [item.path]}}"
    with_items: "{{ output.files }}"

  - debug: var=Folders
